=== patrickingle/phpjobseer/trunk/PJSDBDef.dtd
<!ELEMENT database (tables*,procedures*,functions*)>
<!ELEMENT tables (table*)>

<!ELEMENT table (columns+,keys*,triggers*,rows*)>
<!ATTLIST table name CDATA #REQUIRED
                charset CDATA "latin1"
                collation CDATA "latin1_swedish_ci"
                engine CDATA #IMPLIED>

<!ELEMENT columns (column+)>

<!ELEMENT column EMPTY>
<!ATTLIST column name CDATA #REQUIRED
                 type CDATA #REQUIRED
                 nullable (FALSE|TRUE) #REQUIRED
                 default CDATA #IMPLIED
                 extra CDATA #IMPLIED>

<!ELEMENT keys (key*)>

<!ELEMENT key (memberColumn*,reference*,memberColumn*)>
<!ATTLIST key name CDATA #REQUIRED
              type CDATA #REQUIRED
              onDelete (CASCADE|NOACTION) #IMPLIED
              onUpdate (CASCADE|NOACTION) #IMPLIED>

<!ELEMENT memberColumn EMPTY>
<!ATTLIST memberColumn name CDATA #REQUIRED>

<!ELEMENT reference (#PCDATA)>
<!ATTLIST reference table CDATA #REQUIRED>

<!ELEMENT triggers (trigger*)>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger name CDATA #REQUIRED
                  when (BEFORE|AFTER) #REQUIRED
                  event (INSERT|UPDATE|DELETE) #REQUIRED>

<!ELEMENT rows (row*)>

<!ELEMENT row (field*)>

<!ELEMENT field (#PCDATA)>
<!ATTLIST field name CDATA #REQUIRED>

<!ELEMENT procedures (procedure*)>

<!ELEMENT procedure (#PCDATA)>
<!ATTLIST procedure name CDATA #REQUIRED>

<!ELEMENT functions (function*)>

<!ELEMENT function (#PCDATA)>
<!ATTLIST function name CDATA #REQUIRED>

=== patrickingle/phpjobseer/trunk/PJSDBDef.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE database SYSTEM "PJSDBDef.dtd">
<database>
	<tables>
		<table name="applicationStatus"
		       charset="latin1"
	    	   collation="latin1_swedish_ci"
	    	   engine="InnoDB">
			<columns>
				<column name="applicationStatusId"
				        type="SMALLSERIAL UNSIGNED"
				        nullable="FALSE" />
				<column name="isActive"
				        type="BOOLEAN"
				        nullable="FALSE"
				        default="TRUE" />
				<column name="sortKey"
				        type="SMALLINT UNSIGNED"
				        nullable="FALSE"
				        default="100" />
				<column name="statusValue"
				        type="VARCHAR(50)"
				        nullable="FALSE" />
				<column name="style"
				        type="VARCHAR(4096)"
				        nullable="FALSE" />
				<column name="created"
				        type="TIMESTAMP"
				        nullable="FALSE"
				        default="0000-00-00 00:00:00" />
				<column name="updated"
				        type="TIMESTAMP"
				        nullable="FALSE"
				        default="CURRENT_TIMESTAMP"
				        extra="ON UPDATE CURRENT_TIMESTAMP" />
		    </columns>
			<keys>
			    <key name="applicationStatusIdIdx" type="PRIMARY">
			    	<memberColumn name="applicationStatusId" />
			    </key>
			</keys>
			<triggers>
			</triggers>
			<rows>
				<row>
					<field name="applicationStatusId">1</field>
					<field name="statusValue">FOUND</field>
					<field name="isActive">1</field>
					<field name="sortKey">10</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">2</field>
					<field name="statusValue">CONTACTED</field>
					<field name="isActive">1</field>
					<field name="sortKey">20</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">3</field>
					<field name="statusValue">APPLIED</field>
					<field name="isActive">1</field>
					<field name="sortKey">30</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">4</field>
					<field name="statusValue">INTERVIEWING</field>
					<field name="isActive">1</field>
					<field name="sortKey">40</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">5</field>
					<field name="statusValue">FOLLOWUP</field>
					<field name="isActive">1</field>
					<field name="sortKey">50</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">6</field>
					<field name="statusValue">CHASING</field>
					<field name="isActive">1</field>
					<field name="sortKey">60</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">7</field>
					<field name="statusValue">NETWORKING</field>
					<field name="isActive">1</field>
					<field name="sortKey">70</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">8</field>
					<field name="statusValue">UNAVAILABLE</field>
					<field name="isActive">0</field>
					<field name="sortKey">999</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">9</field>
					<field name="statusValue">INVALID</field>
					<field name="isActive">0</field>
					<field name="sortKey">999</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">10</field>
					<field name="statusValue">DUPLICATE</field>
					<field name="isActive">0</field>
					<field name="sortKey">999</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">11</field>
					<field name="statusValue">CLOSED</field>
					<field name="isActive">0</field>
					<field name="sortKey">999</field>
					<field name="style"></field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
			</rows>
		</table>
		<table name="applicationStatusSummary"
		       charset="latin1"
	    	   collation="latin1_swedish_ci"
	    	   engine="InnoDB">
			<columns>
				<column name="applicationStatusId"
				        type="SMALLINT UNSIGNED"
				        nullable="FALSE" />
				<column name="statusCount"
				        type="SMALLINT UNSIGNED"
				        nullable="FALSE"
				        default="0" />
				<column name="created"
				        type="TIMESTAMP"
				        nullable="FALSE"
				        default="0000-00-00 00:00:00" />
				<column name="updated"
				        type="TIMESTAMP"
				        nullable="FALSE"
				        default="CURRENT_TIMESTAMP"
				        extra="ON UPDATE CURRENT_TIMESTAMP" />
			</columns>
			<keys>
				<key name="applicationStatusId" type="PRIMARY">
					<memberColumn name="applicationStatusId" />
				</key>
				<key name="fk_applicationStatus"
				     type="CONSTRAINT"
				     onDelete="CASCADE"
				     onUpdate="CASCADE">
					<memberColumn name="applicationStatusId" />
					<reference table="applicationStatus">applicationStatusId</reference>
				</key>
			</keys>
			<triggers>
			</triggers>
			<rows>
				<row>
					<field name="applicationStatusId">1</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">2</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">3</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">4</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">5</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">6</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">7</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">8</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">9</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">10</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
				<row>
					<field name="applicationStatusId">11</field>
					<field name="statusCount">0</field>
					<field name="created">2010-10-03 01:03:33</field>
					<field name="updated">2010-10-03 01:03:33</field>
				</row>
			</rows>
		</table>
		<table name="company"
		       charset="latin1"
	    	   collation="latin1_swedish_ci"
		       engine="InnoDB">
			<columns>
				<column name="companyId"
				        type="SMALLSERIAL UNSIGNED"
					    nullable="FALSE"
					    extra="AUTO_INCREMENT" />
				<column name="agencyCompanyId"
				        type="MEDIUMINT UNSIGNED"
				        nullable="TRUE" />
				<column name="companyAddress1"
				        type="VARCHAR(255)"
				        nullable="FALSE"
				        default="" />
				<column name="companyAddress2"
				        type="VARCHAR(255)"
				        nullable="FALSE"
				        default="" />
				<column name="companyCity"
				        type="VARCHAR(60)"
				        nullable="TRUE"
				        default="" />
				<column name="companyName"
				        type="VARCHAR(100)"
				        nullable="FALSE"
				        default="" />
				<column name="companyPhone"
				        type="INT(10) UNSIGNED"
				        nullable="TRUE" />
				<column name="companyState"
				        type="CHAR(2)"
				        nullable="FALSE"
				        default="" />
				<column name="companyZip"
